// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// eStep
NumericMatrix eStep(NumericVector x, NumericVector N, NumericVector mu, NumericVector pi);
RcppExport SEXP moimix_eStep(SEXP xSEXP, SEXP NSEXP, SEXP muSEXP, SEXP piSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N(NSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pi(piSEXP);
    __result = Rcpp::wrap(eStep(x, N, mu, pi));
    return __result;
END_RCPP
}
