# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute eStep for binomial mixture model
#' @export
eStep <- function(x, N, mu, pi) {
    .Call('moimix_eStep', PACKAGE = 'moimix', x, N, mu, pi)
}

